export const dataTable = [
  {
    authorNameOriginal: "name",
    authorNameTranslit: "translitname",
    titleOriginal: "title",
    titleTranslit: "translittitle",
    language: "arabic",
    genre: "genre",
    textType: "print",
    date: "10",
    date_ce: "10",
    dimensionLabel: "M",
  },
  {
    authorNameOriginal: "print",
    authorNameTranslit: "translitname",
    titleOriginal: "title",
    titleTranslit: "translittitle",
    language: "turkish",
    genre: "genre",
    textType: "type",
    date: "60",
    date_ce: "10",
    dimensionLabel: "M",
  },
  {
    authorNameOriginal: "LIAMBAKAR",
    authorNameTranslit: "query",
    titleOriginal: "title",
    titleTranslit: "translittitle3",
    language: "language",
    genre: "genre",
    textType: "type",
    date: "50",
    date_ce: "10",
    dimensionLabel: "M",
  },
  {
    authorNameOriginal: "zSujoy",
    authorNameTranslit: "translitname",
    titleOriginal: "title",
    titleTranslit: "translittitle",
    language: "Turkish",
    genre: "genre",
    textType: "print",
    date: "700",
    date_ce: "10",
    dimensionLabel: "M",
  },
  {
    authorNameOriginal: "zzname4",
    authorNameTranslit: "translitname",
    titleOriginal: "title",
    titleTranslit: "translittitle",
    language: "language",
    genre: "genre",
    textType: "type",
    date: "600",
    date_ce: "10",
    dimensionLabel: "M",
  },
  {
    authorNameOriginal: "name5",
    authorNameTranslit: "translitname",
    titleOriginal: "title",
    titleTranslit: "translittitle",
    language: "language",
    genre: "genre",
    textType: "print",
    date: "500",
    date_ce: "10",
    dimensionLabel: "M",
  },
  {
    authorNameOriginal: "name6",
    authorNameTranslit: "translitname",
    titleOriginal: "title",
    titleTranslit: "translittitle",
    language: "Arabic",
    genre: "genreQuery",
    textType: "MANUscript",
    date: "1000",
    date_ce: "10",
    dimensionLabel: "L",
  },
  {
    authorNameOriginal: "name7",
    authorNameTranslit: "translitname",
    titleOriginal: "title",
    titleTranslit: "translittitle",
    language: "language",
    genre: "genre",
    textType: "manuscript",
    date: "4",
    date_ce: "10",
    dimensionLabel: "S",
  },
];
